version: '3'
services:
  my-vue2-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src  # Optional: if you want to mount the source code for live changes
